"""initial schema

Revision ID: 7ad585bfaa5d
Revises: 
Create Date: 2026-08-29 23:05:29.115645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad585bfaa5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=60), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('camera_id', sa.String(length=60), nullable=True),
    sa.Column('zone_id', sa.String(length=60), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_event_type'), 'alerts', ['event_type'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('zone_id', sa.String(length=60), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.String(length=60), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('camera_id', sa.String(length=60), nullable=True),
    sa.Column('zone_id', sa.String(length=60), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('monetization_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.String(length=60), nullable=True),
    sa.Column('metric_name', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monetization_metrics_timestamp'), 'monetization_metrics', ['timestamp'], unique=False)
    op.create_table('occupancy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.String(length=60), nullable=True),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupancy_timestamp'), 'occupancy', ['timestamp'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_timestamp'), 'system_events', ['timestamp'], unique=False)
    op.create_table('visibility_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.String(length=60), nullable=True),
    sa.Column('metric_name', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visibility_metrics_timestamp'), 'visibility_metrics', ['timestamp'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=60), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_camera_id'), 'detections', ['camera_id'], unique=False)
    op.create_index(op.f('ix_detections_timestamp'), 'detections', ['timestamp'], unique=False)
    op.create_table('entries_exits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=60), nullable=False),
    sa.Column('zone_id', sa.String(length=60), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_exits_camera_id'), 'entries_exits', ['camera_id'], unique=False)
    op.create_index(op.f('ix_entries_exits_timestamp'), 'entries_exits', ['timestamp'], unique=False)
    op.create_table('queue_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=60), nullable=False),
    sa.Column('zone_id', sa.String(length=60), nullable=True),
    sa.Column('queue_length', sa.Integer(), nullable=False),
    sa.Column('avg_wait_seconds', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_stats_camera_id'), 'queue_stats', ['camera_id'], unique=False)
    op.create_index(op.f('ix_queue_stats_timestamp'), 'queue_stats', ['timestamp'], unique=False)
    op.create_table('shelf_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=60), nullable=False),
    sa.Column('zone_id', sa.String(length=60), nullable=True),
    sa.Column('event_label', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelf_events_camera_id'), 'shelf_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_shelf_events_timestamp'), 'shelf_events', ['timestamp'], unique=False)
    op.create_table('tracks',
    sa.Column('track_id', sa.String(length=60), nullable=False),
    sa.Column('camera_id', sa.String(length=60), nullable=False),
    sa.Column('class_name', sa.String(length=60), nullable=False),
    sa.Column('zone_id', sa.String(length=60), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('track_id')
    )
    op.create_index(op.f('ix_tracks_camera_id'), 'tracks', ['camera_id'], unique=False)
    op.create_index(op.f('ix_tracks_last_seen'), 'tracks', ['last_seen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_last_seen'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_camera_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_shelf_events_timestamp'), table_name='shelf_events')
    op.drop_index(op.f('ix_shelf_events_camera_id'), table_name='shelf_events')
    op.drop_table('shelf_events')
    op.drop_index(op.f('ix_queue_stats_timestamp'), table_name='queue_stats')
    op.drop_index(op.f('ix_queue_stats_camera_id'), table_name='queue_stats')
    op.drop_table('queue_stats')
    op.drop_index(op.f('ix_entries_exits_timestamp'), table_name='entries_exits')
    op.drop_index(op.f('ix_entries_exits_camera_id'), table_name='entries_exits')
    op.drop_table('entries_exits')
    op.drop_index(op.f('ix_detections_timestamp'), table_name='detections')
    op.drop_index(op.f('ix_detections_camera_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_visibility_metrics_timestamp'), table_name='visibility_metrics')
    op.drop_table('visibility_metrics')
    op.drop_index(op.f('ix_system_events_timestamp'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_occupancy_timestamp'), table_name='occupancy')
    op.drop_table('occupancy')
    op.drop_index(op.f('ix_monetization_metrics_timestamp'), table_name='monetization_metrics')
    op.drop_table('monetization_metrics')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_event_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
