"""Standardized data contracts shared across the whole system.

Nothing here knows about SQLite, PySide6, Streamlit, RabbitMQ, or any
hardware. These are the shapes every module agrees to speak in — including
the teammate's eventual GStreamer/Qualcomm/tracker code.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Optional

from pydantic import BaseModel, Field

from core.enums import EventType, Severity


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Frame(BaseModel):
    """A single video frame, however it was captured (mock, file, or a real
    GStreamer receiver later). Only carries metadata here — the actual pixel
    buffer is deliberately NOT modeled as a Pydantic field, since that's a
    heavy/binary payload best passed around out-of-band by adapters."""

    camera_id: str
    timestamp: datetime = Field(default_factory=_utcnow)
    width: int
    height: int
    frame_index: int = 0


class Detection(BaseModel):
    """One detected object in one frame. Produced by an InferenceEngine
    adapter (mock now, Qualcomm Detectron2 later — teammate's)."""

    camera_id: str
    timestamp: datetime = Field(default_factory=_utcnow)
    class_id: int
    class_name: str
    confidence: float = Field(ge=0.0, le=1.0)
    bbox: tuple[float, float, float, float]  # x1, y1, x2, y2
    metadata: dict[str, Any] = Field(default_factory=dict)


class Track(BaseModel):
    """A detection with a persistent identity across frames. Produced by a
    Tracker adapter (mock now, real tracker later — teammate's)."""

    track_id: str
    camera_id: str
    class_name: str
    bbox: tuple[float, float, float, float]
    confidence: float = Field(ge=0.0, le=1.0)
    first_seen: datetime
    last_seen: datetime
    zone_id: Optional[str] = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class AnalyticsResult(BaseModel):
    """One computed metric from an analytics module — e.g. a people count,
    a queue length, an occupancy percentage. Generic enough to cover all the
    analytics/* modules without a separate Pydantic model per metric type."""

    metric_name: str
    camera_id: Optional[str] = None
    zone_id: Optional[str] = None
    value: float
    unit: Optional[str] = None
    timestamp: datetime = Field(default_factory=_utcnow)
    metadata: dict[str, Any] = Field(default_factory=dict)


class Event(BaseModel):
    """A standardized event, generated by analytics/event_engine.py and
    consumed by storage, the alert manager, PySide6, and (later) RabbitMQ.
    Never hard-wired to any one consumer."""

    event_id: str
    event_type: EventType
    timestamp: datetime = Field(default_factory=_utcnow)
    camera_id: Optional[str] = None
    zone_id: Optional[str] = None
    severity: Severity = Severity.INFO
    message: str
    metadata: dict[str, Any] = Field(default_factory=dict)


class Alert(BaseModel):
    """A stateful alert derived from one or more events, managed by
    alerts/alert_manager.py (active/acknowledged/resolved + cooldown)."""

    alert_id: str
    event_type: EventType
    severity: Severity
    camera_id: Optional[str] = None
    zone_id: Optional[str] = None
    message: str
    status: str = "active"  # active, acknowledged, resolved
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)
    metadata: dict[str, Any] = Field(default_factory=dict)


class EntryExitReading(BaseModel):
    """Emitted by analytics/entry_exit.py when a track appears/disappears.
    Persisted via storage.writer.write_entry_exit(camera_id, zone_id,
    direction) — direction is "in" or "out", matching the convention
    already established by storage/repositories.py::entry_exit_counts()."""

    camera_id: str
    zone_id: Optional[str] = None
    direction: str  # "in" or "out"
    timestamp: datetime = Field(default_factory=_utcnow)


class ShelfActivity(BaseModel):
    """Emitted by analytics/shelf_monitor.py when a track dwells near a
    shelf zone past threshold. Persisted via
    storage.writer.write_shelf_event(camera_id, zone_id, event_label)."""

    camera_id: str
    zone_id: Optional[str] = None
    event_label: str
    timestamp: datetime = Field(default_factory=_utcnow)


class CameraStatus(BaseModel):
    camera_id: str
    online: bool
    last_seen: Optional[datetime] = None
    fps: Optional[float] = None
    resolution: Optional[str] = None
    bitrate_kbps: Optional[float] = None


class SystemStatus(BaseModel):
    timestamp: datetime = Field(default_factory=_utcnow)
    cameras_online: int
    cameras_total: int
    rabbitmq_connected: bool
    database_ok: bool
    notes: Optional[str] = None
